package com.example.mvvm
//new
data class Shop(
    val address: String,
    val banner: String,
    val commissionRate: Int,
    val contactNumber: String,
    val deleted: Boolean,
    val deliveryCharge: Int,
    val description: String,
    val hub: Any,
    val hubId: Any,
    val id: String,
    val isFlagshipShop: Boolean,
    val isFreeDelivery: Boolean,
    val isInclusiveVat: Boolean,
    val isPopularShop: Boolean,
    val isPrimeShop: Boolean,
    val location: Location,
    val logo: String,
    val minimumAmountForFreeDelivery: Int,
    val name: String,
    val noVat: Boolean,
    val numberOfRating: Int,
    val rating: Int,
    val restaurantDiscount: Int,
    val slug: String,
    val status: String,
    val timeRemaining: Int,
    val timeSlots: List<TimeSlot>,
    val totalDiscount: Int,
    val type: String,
    val username: String,
    val vat: Int,
    val versionCode: Any
)